services:
  interface:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/maschsee_videos:/static/video/
      - /mnt/geojson_files:/geojsonfiles
    networks:
      - haix-network
    command: flask --app main.py run --host=0.0.0.0
    depends_on:
      postgis_container:
        condition: service_healthy
      path_planning_vrpy:
        condition: service_started
      estimate_areas_of_interest:
        condition: service_started

  postgis_container:
    build: sql/.
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=secret"
    networks:
      - haix-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

  path_planning_vrpy:
    image: git.ni.dfki.de:5050/hai-x/path-planning/cvrp-with-vrpy:latest
    networks:
      - haix-network
    ports:
      - "10002:10002"

  estimate_areas_of_interest:
    #image: ndviareas
    image: git.ni.dfki.de:5050/hai-x/area-of-interest-detectors/estimate-weeding-areas-from-ndvi:latest
    networks:
      - haix-network
    environment:
      - sh_client_id=${sh_client_id}
      - sh_client_secret=${sh_client_secret}
      - sh_instance_id=${sh_instance_id}
    ports:
      - "10003:10003"

  evaluation_service:
    image: git.ni.dfki.de:5050/hai-x/evaluation/evaluation-of-satellite-seagrass-detection-with-onboard-camera:latest
    networks:
      - haix-network
    ports:
      - "10005:10005"
    volumes:
      - /mnt/maschsee_videos:/data/rosbags
    env_file:
      - .env

  data_extraction:
    image: git.ni.dfki.de:5050/hai-x/haix_tools/ros-data-extraction-api:latest
    networks:
      - haix-network
    ports:
      - "10006:10006"
    volumes:
      - /mnt/maschsee_videos:/home/docker/rosbags

  bathymetry_service:
    image: git.ni.dfki.de:5050/hai-x/data/bathymetry/bathymetry:latest
    networks:
      - haix-network
    ports:
      - "10007:10005"

  apa_index_service:
    image: git.ni.dfki.de:5050/hai-x/data/sentinel-2:latest
    networks:
      - haix-network
    ports:
      - "10008:10003"

  capacitated_aoi_service:
    image: git.ni.dfki.de:5050/hai-x/area-of-interest-detectors/density_based_clustering:latest
    networks:
      - haix-network
    ports:
      - "10010:10010"

  capacitated_path_service:
    image: git.ni.dfki.de:5050/hai-x/path-planning/cvrp_with_capacity_clusters/capicitated_cluster_cvrp:latest
    networks:
      - haix-network
    ports:
      - "10011:10011"


networks:
  haix-network:
    name: haix-network
