services:
  interface:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/maschsee_videos:/static/video/
      - /mnt/geojson_files:/geojsonfiles
    networks:
      - haix-network
    command: flask --app main.py run --host=0.0.0.0
    depends_on:
      postgis_container:
        condition: service_healthy
      path_planning_vrpy:
        condition: service_started
      estimate_areas_of_interest:
        condition: service_started

  postgis_container:
    build: sql/.
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=secret"
    networks:
      - haix-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]

  path_planning_vrpy:
    build: services/cvrp-with-vrpy/.
    networks:
      - haix-network
    ports:
      - "10002:10002"

  estimate_areas_of_interest:
    #image: ndviareas
    build: services/estimate_areas_of_interest/.
    networks:
      - haix-network
    ports:
      - "10003:10003"

  evaluation_service:
    build: services/evaluation_service/.
    networks:
      - haix-network
    ports:
      - "10005:10005"
    volumes:
      - /mnt/maschsee_videos:/data/rosbags

  ros-noetic:
    build:
      context: services/data_extraction/dockers/
      dockerfile: Dockerfile.base
      target: ros-noetic
    container_name: ros-noetic
    network_mode: host

  api-data-extraction:
    build:
      context: ./
      dockerfile: services/data_extraction/dockers/Dockerfile.ros.api_data_extraction
      additional_contexts:
        base_image: "service:ros-noetic"
    container_name: api-data-extraction
    volumes:
      - /mnt/maschsee_videos:/home/docker/rosbags
    ports:
      - "10006:10006"
    command: python3 -m uvicorn scripts.api_data_extraction:app --host 0.0.0.0 --port 10006

  bathymetry_service:
    build: services/bathymetry_service/.
    networks:
      - haix-network
    ports:
      - "10007:10005"

  apa_index_service:
    build: services/apa_index_service/.
    networks:
      - haix-network
    ports:
      - "10008:10003"

  capacitated_aoi_service:
    build: services/capacitated_aoi_service/.
    networks:
      - haix-network
    ports:
      - "10010:10010"

  capacitated_path_service:
    build: services/capacitated_path_service/.
    networks:
      - haix-network
    ports:
      - "10011:10011"


networks:
  haix-network:
    name: haix-network