# syntax=docker/dockerfile:1
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy project
COPY ./data ./data/
COPY ./src ./src/
COPY ./assets ./assets/
COPY main.py .

# Default command: run the main script
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10005"]
